services:
  web:
    # Build the image from the Dockerfile in the current directory
    build: .

    # Host the Flask application on port 443
    ports:
      - "443:443"

    # Create a `watch` configuration to update the application
    # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/

        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml