name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: "build image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: ankiflask:latest
          cache-from: type=gha,scope=ankiflask
          cache-to: type=gha,mode=min,scope=ankiflask
          outputs: type=docker,dest=/tmp/ankiflask.tar

#      - name: Build and export (multistage)
#        uses: docker/build-push-action@v6
#        with:
#          file: multistage.Dockerfile
#          tags: ankiflask-multistage:latest
#          cache-from: type=gha,scope=ankiflask-multistage
#          cache-to: type=gha,mode=min,scope=ankiflask-multistage
#          outputs: type=docker,dest=/tmp/ankiflask-multistage.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ankiflask
          path: /tmp/ankiflask.tar

#      - name: Upload artifact (multistage)
#        uses: actions/upload-artifact@v4
#        with:
#          name: ankiflask-multistage
#          path: /tmp/ankiflask-multistage.tar

  test:
    name: "test image"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ankiflask
          path: /tmp

#      - name: Download artifact (multistage)
#        uses: actions/download-artifact@v4
#        with:
#          name: ankiflask-multistage
#          path: /tmp

      - name: Load images
        run: |
          docker load --input /tmp/ankiflask.tar
          docker image ls -a

      - name: Test Flask server
        run: |
          docker run -d --name ankiflask-container -p 443:443 ankiflask:latest
          sleep 10  # Wait for the server to start
          docker logs ankiflask-container
          curl -f https://localhost:443/anki_flask/test || docker logs ankiflask-container
          docker stop ankiflask-container
          docker rm ankiflask-container

      - name: Test Docker compose
        run: |
          docker compose up --watch -d
          docker compose down

  deploy:
    name: "deploy image"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ankiflask
          path: /tmp

      - name: Load Docker image
        run: docker load --input /tmp/ankiflask.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and push Docker image
        run: |
          docker tag ankiflask:latest hapgilmore/ankiflask:latest
          docker push hapgilmore/ankiflask:latest