deploy:
  name: "deploy image"
  runs-on: ubuntu-latest
  needs: test
  steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: hapgilmore/ankiflask:latest

    - name: Deploy to Docker Desktop
      run: |
        docker pull hapgilmore/ankiflask:latest
        docker stop ankiflask-container || true
        docker rm ankiflask-container || true
        docker run -d --name ankiflask-container -p 443:443 hapgilmore/ankiflask:latest